# Azure Virtual Machine Configuration
# Generated by MCP Infrastructure Orchestrator
# Request ID: 45163141

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
}

# Create resource group (if not exists)
resource "azurerm_resource_group" "main" {
  name     = "InfraOps-RG"
  location = "eastus"

  tags = {
    environment = "production"
    created_by  = "mcp-infrastructure"
    request_id  = "45163141"
  }
}

# Create virtual network (if not exists)
resource "azurerm_virtual_network" "main" {
  name                = "InfraOps-Vnet"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  tags = {
    request_id = "45163141"
  }
}

# Create subnet
resource "azurerm_subnet" "internal" {
  name                 = "subnet-1"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = ["10.0.2.0/24"]
}

# Create network interface
resource "azurerm_network_interface" "main" {
  name                = "vm-45163141-nic"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  ip_configuration {
    name                          = "testconfiguration1"
    subnet_id                     = azurerm_subnet.internal.id
    private_ip_address_allocation = "Static"
    private_ip_address        = "192.168.1.100"
  }

  tags = {
    request_id = "45163141"
  }
}

# Create virtual machine
resource "azurerm_linux_virtual_machine" "main" {
  name                = "vm-45163141"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  vm_size             = "Standard_B4ms"

  admin_username = "azureuser"

  admin_ssh_key {
    username   = "azureuser"
    public_key = file("~/.ssh/id_rsa.pub")
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Premium_LRS"
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-focal"
    sku       = "20_04-lts-gen2"
    version   = "latest"
  }

  tags = {
    environment = "production"
    created_by  = "mcp-infrastructure"
    request_id  = "45163141"
  }

  network_interface_ids = [
    azurerm_network_interface.main.id,
  ]

  depends_on = [
    azurerm_network_interface.main,
  ]
}

output "vm_id" {
  value = azurerm_linux_virtual_machine.main.id
}

output "vm_public_ip" {
  value = "Assigned through Load Balancer or Application Gateway"
}

output "vm_private_ip" {
  value = azurerm_network_interface.main.private_ip_address
}
