# Azure Virtual Machine Configuration
# Generated by MCP Infrastructure Orchestrator
# Request ID: 708abe3b

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
}

variable "environment" {
  type        = string
  default     = "production"
  description = "Environment name"
}

variable "project_name" {
  type        = string
  default     = "mcp-infrastructure"
  description = "Project name"
}

variable "location" {
  type        = string
  default     = "eastus"
  description = "Azure region for resources"
}

variable "vm_size" {
  type        = string
  default     = "Standard_D2s_v3"
  description = "Azure VM size"
}

variable "resource_group_name" {
  type        = string
  default     = "infraops-rg-2"
  description = "Resource group name"
}

variable "vnet_name" {
  type        = string
  default     = "InfraOps-Vnet"
  description = "Virtual network name"
}

variable "subnet_name" {
  type        = string
  default     = "Staff"
  description = "Subnet name"
}

variable "vm_name" {
  type        = string
  default     = "vm-708abe3b"
  description = "Virtual machine name"
}

variable "private_ip_address" {
  type        = string
  default     = ""
  description = "Private IP address for the VM (optional, leave empty for dynamic)"
}

# Look up existing resource group
data "azurerm_resource_group" "main" {
  name = var.resource_group_name
}

# Look up existing virtual network
data "azurerm_virtual_network" "main" {
  name                = var.vnet_name
  resource_group_name = data.azurerm_resource_group.main.name
}

# Look up existing subnet
data "azurerm_subnet" "internal" {
  name                 = var.subnet_name
  virtual_network_name = data.azurerm_virtual_network.main.name
  resource_group_name  = data.azurerm_resource_group.main.name
}

# Create network interface
resource "azurerm_network_interface" "main" {
  name                = "${var.vm_name}-nic"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name

  ip_configuration {
    name                          = "primary"
    subnet_id                     = data.azurerm_subnet.internal.id
    private_ip_address_allocation = "Dynamic"
  }

  tags = {
    request_id = "708abe3b"
  }
}

# Create virtual machine
resource "azurerm_linux_virtual_machine" "main" {
  name                = var.vm_name
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  size                = var.vm_size

  admin_username = "azureuser"
  disable_password_authentication = false

  admin_password = "P@ssw0rd123!"

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Premium_LRS"
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-focal"
    sku       = "20_04-lts-gen2"
    version   = "latest"
  }

  tags = {
    environment = var.environment
    created_by  = var.project_name
    request_id  = "708abe3b"
  }

  network_interface_ids = [
    azurerm_network_interface.main.id,
  ]

  depends_on = [
    azurerm_network_interface.main,
  ]
}

output "vm_id" {
  value       = azurerm_linux_virtual_machine.main.id
  description = "The ID of the created virtual machine"
}

output "vm_private_ip" {
  value       = azurerm_network_interface.main.private_ip_address
  description = "Private IP address of the virtual machine"
}

output "resource_group_id" {
  value       = data.azurerm_resource_group.main.id
  description = "The ID of the resource group"
}
