# Azure Subnets Configuration
# Generated by MCP Infrastructure Orchestrator
# Request ID: 4cf00e0e

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
}

# Subnets in Virtual Network: InfraOps-Vnet
# Resource Group: the

resource "azurerm_subnet" "staff" {
  name                 = "Staff"
  resource_group_name  = "the"
  virtual_network_name = "InfraOps-Vnet"
  address_prefixes     = ["10.10.0.0/24"]
}

resource "azurerm_subnet" "infra_ops" {
  name                 = "Infra-Ops"
  resource_group_name  = "the"
  virtual_network_name = "InfraOps-Vnet"
  address_prefixes     = ["10.10.1.0/24"]
}


# Outputs
output "subnet_staff_id" {
  description = "The ID of subnet Staff"
  value       = azurerm_subnet.staff.id
}

output "subnet_infra_ops_id" {
  description = "The ID of subnet Infra-Ops"
  value       = azurerm_subnet.infra_ops.id
}

