# FIREWALL CONFIGURATION
# Azure Firewall Configuration
# Generated by MCP Infrastructure Orchestrator
# Request ID: 0dc77f4f

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
}

variable "location" {
  type        = string
  default     = "eastus"
  description = "Azure region for resources"
}

variable "resource_group_name" {
  type        = string
  default     = "InfraOps-RG"
  description = "Resource group name"
}

variable "firewall_name" {
  type        = string
  default     = "Gems-Road-FW-01"
  description = "Firewall name"
}

variable "vnet_name" {
  type        = string
  default     = "InfraOps-Vnet"
  description = "Virtual Network name for AzureFirewallSubnet"
}

# Look up existing resource group
data "azurerm_resource_group" "main" {
  name = var.resource_group_name
}

# Look up existing virtual network
data "azurerm_virtual_network" "main" {
  name                = var.vnet_name
  resource_group_name = data.azurerm_resource_group.main.name
}

# Create public IP for firewall
resource "azurerm_public_ip" "fw" {
  name                = "${var.firewall_name}-pip"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  allocation_method   = "Static"
  sku                 = "Standard"

  tags = {
    request_id = "0dc77f4f"
  }
}

# Get or create AzureFirewallSubnet
data "azurerm_subnet" "fw_subnet" {
  name                 = "AzureFirewallSubnet"
  virtual_network_name = data.azurerm_virtual_network.main.name
  resource_group_name  = data.azurerm_resource_group.main.name
}

# Create Azure Firewall
resource "azurerm_firewall" "main" {
  name                = var.firewall_name
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  sku_name            = "AZFW_VNet"
  sku_tier            = "Standard"

  ip_configuration {
    name                 = "configuration"
    subnet_id            = data.azurerm_subnet.fw_subnet.id
    public_ip_address_id = azurerm_public_ip.fw.id
  }

  tags = {
    request_id = "0dc77f4f"
  }
}

# Create firewall network rule collection for basic connectivity
resource "azurerm_firewall_network_rule_collection" "main" {
  name                = "allow-internal"
  azure_firewall_name = azurerm_firewall.main.name
  resource_group_name = data.azurerm_resource_group.main.name
  priority            = 100
  action              = "Allow"

  rule {
    name                  = "AllowAll"
    protocols             = ["TCP", "UDP"]
    source_addresses      = ["*"]
    destination_addresses = ["*"]
    destination_ports     = ["*"]
  }
}

output "firewall_id" {
  value       = azurerm_firewall.main.id
  description = "The ID of the created firewall"
}

output "firewall_private_ip" {
  value       = azurerm_firewall.main.ip_configuration[0].private_ip_address
  description = "Private IP address of the firewall"
}

output "firewall_public_ip" {
  value       = azurerm_public_ip.fw.ip_address
  description = "Public IP address of the firewall"
}


# VNET CONFIGURATION
# Azure Virtual Network Configuration
# Generated by MCP Infrastructure Orchestrator
# Request ID: 0dc77f4f

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
}

variable "location" {
  type        = string
  default     = "eastus"
  description = "Azure region for resources"
}

variable "resource_group_name" {
  type        = string
  default     = "InfraOps-RG"
  description = "Resource group name"
}

variable "vnet_name" {
  type        = string
  default     = "Gems-Vnet"
  description = "Virtual Network name"
}

variable "address_space" {
  type        = list(string)
  default     = ["10.10.0.0/16"]
  description = "Virtual Network address space"
}

variable "environment" {
  type        = string
  default     = "production"
  description = "Environment name"
}

variable "project_name" {
  type        = string
  default     = "mcp-infrastructure"
  description = "Project name"
}

# Check if resource group already exists (for idempotency)
data "azurerm_resource_group" "existing" {
  name = var.resource_group_name
}

# Create resource group only if it doesn't exist in Azure
# Use lifecycle ignore_changes to prevent conflicts when state doesn't exist
resource "azurerm_resource_group" "main" {
  name     = var.resource_group_name
  location = var.location

  lifecycle {
    ignore_changes = [tags]
  }

  tags = {
    request_id = "0dc77f4f"
    environment = var.environment
    created_by = var.project_name
  }
}

# Create Virtual Network
resource "azurerm_virtual_network" "main" {
  name                = var.vnet_name
  address_space       = var.address_space
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  tags = {
    request_id = "0dc77f4f"
    environment = var.environment
  }
}

# Create default subnet
resource "azurerm_subnet" "default" {
  name                 = "${var.vnet_name}-subnet-default"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = ["10.10.0.0/24"]
}

output "vnet_id" {
  value       = azurerm_virtual_network.main.id
  description = "The ID of the created Virtual Network"
}

output "vnet_name" {
  value       = azurerm_virtual_network.main.name
  description = "The name of the created Virtual Network"
}

output "resource_group_id" {
  value       = azurerm_resource_group.main.id
  description = "The ID of the resource group"
}

output "subnet_id" {
  value       = azurerm_subnet.default.id
  description = "The ID of the default subnet"
}
