# Azure Virtual Network Configuration
# Generated by MCP Infrastructure Orchestrator
# Request ID: 43cd73e5

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
}

variable "location" {
  type        = string
  default     = "eastus"
  description = "Azure region for resources"
}

variable "resource_group_name" {
  type        = string
  default     = "InfraOps-RG"
  description = "Resource group name"
}

variable "vnet_name" {
  type        = string
  default     = "vnet1"
  description = "Virtual Network name"
}

variable "address_space" {
  type        = list(string)
  default     = ["10.10.0.0/16"]
  description = "Virtual Network address space"
}

variable "environment" {
  type        = string
  default     = "production"
  description = "Environment name"
}

variable "project_name" {
  type        = string
  default     = "mcp-infrastructure"
  description = "Project name"
}

# Check if resource group already exists (for idempotency)
data "azurerm_resource_group" "existing" {
  name = var.resource_group_name
}

# Create resource group only if it doesn't exist in Azure
# Use lifecycle ignore_changes to prevent conflicts when state doesn't exist
resource "azurerm_resource_group" "main" {
  name     = var.resource_group_name
  location = var.location

  lifecycle {
    ignore_changes = [tags]
  }

  tags = {
    request_id = "43cd73e5"
    environment = var.environment
    created_by = var.project_name
  }
}

# Create Virtual Network
resource "azurerm_virtual_network" "main" {
  name                = var.vnet_name
  address_space       = var.address_space
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name

  tags = {
    request_id = "43cd73e5"
    environment = var.environment
  }
}

# Create default subnet
resource "azurerm_subnet" "default" {
  name                 = "${var.vnet_name}-subnet-default"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = ["10.10.0.0/24"]
}

output "vnet_id" {
  value       = azurerm_virtual_network.main.id
  description = "The ID of the created Virtual Network"
}

output "vnet_name" {
  value       = azurerm_virtual_network.main.name
  description = "The name of the created Virtual Network"
}

output "resource_group_id" {
  value       = azurerm_resource_group.main.id
  description = "The ID of the resource group"
}

output "subnet_id" {
  value       = azurerm_subnet.default.id
  description = "The ID of the default subnet"
}
