# Azure Firewall and Virtual Network Configuration
# Generated by MCP Infrastructure Orchestrator - Combined Deployment
# Request ID: 72361e74

terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
}

provider "azurerm" {
  features {}
}

# ====== VIRTUAL NETWORK RESOURCES ======

data "azurerm_resource_group" "main" {
  name = "In"
}

resource "azurerm_virtual_network" "main" {
  name                = "test-vnet"
  address_space       = ["10.10.0.0/16"]
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name

  tags = {
    request_id = "72361e74"
    created_by = "MCP-Infrastructure"
  }
}

resource "azurerm_subnet" "internal" {
  name                 = "Staff"
  virtual_network_name = azurerm_virtual_network.main.name
  resource_group_name  = data.azurerm_resource_group.main.name
  address_prefixes     = ["10.10.0.0/24"]
}

resource "azurerm_subnet" "firewall" {
  name                 = "AzureFirewallSubnet"
  virtual_network_name = azurerm_virtual_network.main.name
  resource_group_name  = data.azurerm_resource_group.main.name
  address_prefixes     = ["10.10.1.0/24"]
}

# ====== FIREWALL RESOURCES ======

resource "azurerm_public_ip" "firewall" {
  name                = "test-fw-pip"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  allocation_method   = "Static"
  sku                 = "Standard"

  tags = {
    request_id = "72361e74"
  }
}

resource "azurerm_firewall" "main" {
  name                = "test-fw"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name
  sku_name            = "AZFW_VNet"
  sku_tier            = "Standard"

  ip_configuration {
    name                 = "configuration"
    subnet_id            = azurerm_subnet.firewall.id
    public_ip_address_id = azurerm_public_ip.firewall.id
  }

  tags = {
    request_id = "72361e74"
  }
}

resource "azurerm_firewall_network_rule_collection" "main" {
  name                = "allow-internal"
  azure_firewall_name = azurerm_firewall.main.name
  resource_group_name = data.azurerm_resource_group.main.name
  priority            = 100
  action              = "Allow"

  rule {
    name                  = "AllowAll"
    protocols             = ["TCP", "UDP"]
    source_addresses      = ["*"]
    destination_addresses = ["*"]
    destination_ports     = ["*"]
  }
}

# ====== OUTPUTS ======

output "firewall_id" {
  value       = azurerm_firewall.main.id
  description = "The ID of the created firewall"
}

output "firewall_private_ip" {
  value       = azurerm_firewall.main.ip_configuration[0].private_ip_address
  description = "Private IP address of the firewall"
}

output "firewall_public_ip" {
  value       = azurerm_public_ip.firewall.ip_address
  description = "Public IP address of the firewall"
}

output "vnet_id" {
  value       = azurerm_virtual_network.main.id
  description = "The ID of the created virtual network"
}

output "vnet_address_space" {
  value       = azurerm_virtual_network.main.address_space
  description = "The address space of the virtual network"
}
